<!DOCTYPE html>
<html lang="en"><head>
<script src="6.regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="6.regression_files/libs/quarto-html/tabby.min.js"></script>
<script src="6.regression_files/libs/quarto-html/popper.min.js"></script>
<script src="6.regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="6.regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="6.regression_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="6.regression_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.39">

  <meta name="author" content="Dr.&nbsp;Muhammed Fatih TÜZEN">
  <title>R Programlama ile Veri Analizi</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="6.regression_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="6.regression_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="6.regression_files/libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link rel="stylesheet" href="custom.css">
  <link href="6.regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="6.regression_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="6.regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="6.regression_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">R Programlama ile Veri Analizi</h1>
  <p class="subtitle">Doğrusal Regresyon Analizi</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Muhammed Fatih TÜZEN 
</div>
</div>
</div>

  <p class="date">16-05-2025</p>
</section>
<section id="sunum-planı" class="slide level2">
<h2>Sunum Planı</h2>
<div>
<div>
<ul>
<li><strong>Doğrusal Regresyon Nedir?</strong></li>
<li><strong>Varsayımlar</strong></li>
<li><strong>Artık Analizi</strong></li>
<li><strong>Model Performansı</strong></li>
<li><strong>Dikkat Edilecek Hususlar</strong></li>
<li><strong>Faydalı Kaynaklar</strong></li>
</ul>
</div>
<div>
<p>📦 Ders Materyalleri: <a href="https://github.com/MFatihTuzen/UYIK-R" class="uri">https://github.com/MFatihTuzen/UYIK-R</a></p>
</div>
</div>
</section>
<section id="doğrusal-regresyon-nedir" class="slide level2">
<h2>📊 Doğrusal Regresyon Nedir?</h2>
<h3 id="tanım">🔍 Tanım:</h3>
<p>Doğrusal regresyon, <strong>bir bağımlı değişkenin (sonucun)</strong> bir veya birden fazla <strong>bağımsız değişken (girdi)</strong> yardımıyla <strong>doğrusal bir ilişki modeli üzerinden tahmin edilmesini</strong> sağlayan istatistiksel bir yöntemdir.</p>
<h3 id="ne-işe-yarar">🧠 Ne işe yarar?</h3>
<ul>
<li>İki değişken arasındaki ilişkinin gücünü ve yönünü analiz eder.</li>
<li>Nedensellik değil, <strong>ilişki modelleme</strong> amacı taşır.</li>
<li>Gelecekteki gözlemleri tahmin etmek için kullanılabilir.</li>
<li>Makine öğrenmesinin birçok modeline <strong>temel oluşturur.</strong></li>
</ul>
<h3 id="yorum">🧠 Yorum:</h3>
<blockquote>
<p>Regresyon, veriler arasındaki ilişkileri <strong>modellenebilir ve yorumlanabilir</strong> hale getirir.<br>
Ancak <strong>korelasyon ≠ nedensellik</strong> olduğunu asla unutmamak gerekir.</p>
</blockquote>
</section>
<section id="basit-doğrusal-regresyon-temel-model" class="slide level2">
<h2>🧮 Basit Doğrusal Regresyon – Temel Model</h2>
<h3 id="matematiksel-form">📐 Matematiksel Form:</h3>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \varepsilon_i
\]</span></p>
<ul>
<li><span class="math inline">\(y_i\)</span>: bağımlı değişken (tahmin edilmek istenen)</li>
<li><span class="math inline">\(x_i\)</span>: bağımsız değişken (girdi)</li>
<li><span class="math inline">\(\beta_0\)</span>: sabit terim (intercept)</li>
<li><span class="math inline">\(\beta_1\)</span>: eğim (slope)</li>
<li><span class="math inline">\(\varepsilon_i\)</span>: gözlem başına hata (artık)</li>
</ul>
</section>
<section class="slide level2">

<h3 id="parametrelerin-tahmini-ols-ordinary-least-squares">🔧 Parametrelerin Tahmini – OLS (Ordinary Least Squares)</h3>
<p>Amaç: Hata terimlerinin karesinin toplamını minimize eden <span class="math inline">\(\beta_0\)</span> ve <span class="math inline">\(\beta_1\)</span> değerlerini bulmaktır.</p>
<p>Minimize edilen fonksiyon:</p>
<p><span class="math display">\[
\text{SSE} = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 x_i))^2
\]</span></p>
<p>Bu işlemin sonunda <span class="math inline">\(\beta_0\)</span> ve <span class="math inline">\(\beta_1\)</span> için kapalı form çözümler elde edilir.</p>
</section>
<section id="varsayımlar" class="slide level2">
<h2>🧠 Varsayımlar</h2>
<p><strong>Modelin Sağlıklı İşleyebilmesi İçin Gerekli Koşullar</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Varsayım</th>
<th>Açıklama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Lineerlik</strong></td>
<td><span class="math inline">\(x\)</span> ile <span class="math inline">\(y\)</span> arasında doğrusal ilişki olmalı</td>
</tr>
<tr class="even">
<td><strong>Hataların ortalaması sıfırdır</strong></td>
<td><span class="math inline">\(E[\varepsilon_i] = 0\)</span></td>
</tr>
<tr class="odd">
<td><strong>Sabit varyans (homoskedastisite)</strong></td>
<td>Hataların varyansı sabittir</td>
</tr>
<tr class="even">
<td><strong>Bağımsızlık</strong></td>
<td>Gözlemler birbirinden bağımsızdır</td>
</tr>
<tr class="odd">
<td><strong>Normal dağılım</strong></td>
<td>Hatalar normal dağılmıştır (özellikle çıkarım için)</td>
</tr>
</tbody>
</table>
<blockquote>
<p>❗ Varsayımlar sağlanmazsa tahminler tutarsız veya yanlı olabilir.</p>
</blockquote>
</section>
<section id="artık-residual-nedir" class="slide level2">
<h2>📉 Artık (Residual) Nedir?</h2>
<blockquote>
<p>Artık, bir gözlem için modelin yaptığı tahmin ile gerçek değer arasındaki farktır:</p>
</blockquote>
<p><span class="math display">\[
\varepsilon_i = y_i - \hat{y}_i
\]</span></p>
<ul>
<li>Artıklar: modelin ne kadar “yanıldığını” gösterir</li>
<li>Artıkların analizi, modelin doğruluğunu ve varsayımların sağlanıp sağlanmadığını anlamada kullanılır.</li>
</ul>
<div class="columns">
<div class="column" style="width:90%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb1-2"><a href=""></a>y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb1-3"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb1-4"><a href=""></a><span class="fu">plot</span>(x, y, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="st">"Regresyon Doğrusu ve Artıklar"</span>)</span>
<span id="cb1-5"><a href=""></a><span class="fu">abline</span>(model, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb1-6"><a href=""></a><span class="fu">segments</span>(x, y, x, <span class="fu">fitted</span>(model), <span class="at">col =</span> <span class="st">"red"</span>)  <span class="co"># artıklar (hatalar)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="6.regression_files/figure-revealjs/unnamed-chunk-1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<blockquote>
<p>🔴 Kırmızı çizgiler artıkları temsil eder. Modelin her noktada ne kadar saptığını gösterir.</p>
</blockquote>
</section>
<section id="boston-veri-seti-tanıtımı" class="slide level2">
<h2>🏙️ Boston Veri Seti Tanıtımı</h2>
<h3 id="veri-kaynağı">📦 Veri Kaynağı</h3>
<blockquote>
<p><code>Boston</code> veri seti, <strong>MASS</strong> paketinde yer alır.<br>
506 gözlem ve 14 değişkenden oluşur.<br>
Amaç: <strong>Boston’daki konut değerlerini</strong> sosyo-ekonomik ve çevresel değişkenlerle açıklamak.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">library</span>(MASS)</span>
<span id="cb2-2"><a href=""></a><span class="fu">data</span>(<span class="st">"Boston"</span>)</span>
<span id="cb2-3"><a href=""></a><span class="fu">str</span>(Boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   506 obs. of  14 variables:
 $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
 $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
 $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
 $ chas   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
 $ rm     : num  6.58 6.42 7.18 7 7.15 ...
 $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
 $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
 $ rad    : int  1 2 2 3 3 3 5 5 5 5 ...
 $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
 $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
 $ black  : num  397 397 393 395 397 ...
 $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
 $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="ana-değişkenler">🔍 Ana Değişkenler</h3>
<table class="caption-top">
<colgroup>
<col style="width: 54%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Değişken</th>
<th>Açıklama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>medv</code></td>
<td>Median konut değeri (1000 $ cinsinden) → <strong>bağımlı değişken</strong></td>
</tr>
<tr class="even">
<td><code>lstat</code></td>
<td>% düşük sosyo-ekonomik statüdeki insanlar</td>
</tr>
<tr class="odd">
<td><code>rm</code></td>
<td>Ortalama oda sayısı</td>
</tr>
<tr class="even">
<td><code>crim</code></td>
<td>Suç oranı</td>
</tr>
<tr class="odd">
<td><code>nox</code></td>
<td>Azot oksit yoğunluğu (hava kirliliği)</td>
</tr>
<tr class="even">
<td><code>dis</code></td>
<td>Şehir merkezine uzaklık</td>
</tr>
<tr class="odd">
<td><code>ptratio</code></td>
<td>Öğrenci-öğretmen oranı</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>%1940’tan önce inşa edilmiş ev oranı</td>
</tr>
<tr class="odd">
<td><code>indus</code></td>
<td>Endüstriyel alan oranı</td>
</tr>
<tr class="even">
<td><code>chas</code></td>
<td>Charles Nehri kenarında mı? (0 = hayır, 1 = evet)</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="modelleme-amacımız">🎯 Modelleme Amacımız</h3>
<blockquote>
<p>Değişkenlerden biriyle başlayarak konut değerini (<code>medv</code>) tahmin etmek.<br>
Başlangıç: <code>medv ~ lstat</code> → basit regresyon modeli.</p>
</blockquote>
<h3 id="neden-lstat">📌 Neden <code>lstat</code>?</h3>
<ul>
<li>Gelir düzeyini temsil eder</li>
<li>Fiyatlarla ilişkili olması beklenir</li>
<li>Görsel ilişki kolay algılanabilir</li>
<li>İleri adımlarda <code>rm</code>, <code>crim</code> gibi değişkenlerle <strong>çoklu modele</strong> geçeceğiz</li>
</ul>
</section>
<section id="uygulama-basit-doğrusal-regresyon" class="slide level2">
<h2>🧪 Uygulama: Basit Doğrusal Regresyon</h2>
<h3 id="model-medv-lstat">🎯 Model: <code>medv ~ lstat</code></h3>
<blockquote>
<p>Amaç: Düşük sosyo-ekonomik statüdeki insanların oranı arttıkça, konut fiyatı (<code>medv</code>) nasıl değişiyor?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="co"># Modeli kur</span></span>
<span id="cb4-2"><a href=""></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> lstat, <span class="at">data =</span> Boston)</span>
<span id="cb4-3"><a href=""></a>model1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat, data = Boston)

Coefficients:
(Intercept)        lstat  
      34.55        -0.95  </code></pre>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="regresyon-çıktısının-yorumlanması">📋 Regresyon Çıktısının Yorumlanması</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="co"># Model özetini incele</span></span>
<span id="cb6-2"><a href=""></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat, data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.168  -3.990  -1.318   2.034  24.500 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 34.55384    0.56263   61.41   &lt;2e-16 ***
lstat       -0.95005    0.03873  -24.53   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.216 on 504 degrees of freedom
Multiple R-squared:  0.5441,    Adjusted R-squared:  0.5432 
F-statistic: 601.6 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<h3 id="çıktı-bileşenleri">🔍 Çıktı Bileşenleri:</h3>
<ol type="1">
<li><p><strong>Call:</strong><br>
Model formülünü tekrar gösterir: <code>medv ~ lstat</code></p></li>
<li><p><strong>Coefficients:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Terim</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>34.5538</td>
<td>0.5626</td>
<td>61.41</td>
<td>&lt; 2e-16</td>
</tr>
<tr class="even">
<td>lstat</td>
<td>-0.9500</td>
<td>0.0387</td>
<td>-24.54</td>
<td>&lt; 2e-16</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Estimate</strong>: Tahmin edilen katsayı</li>
<li><strong>Std. Error</strong>: Bu tahminin belirsizliği (SE)</li>
<li><strong>t value</strong>: <span class="math inline">\(\frac{\text{Estimate}}{\text{Std.Error}}\)</span></li>
<li><strong>p-value</strong>: Katsayının sıfırdan farklı olup olmadığını test eder</li>
</ul>
<blockquote>
<p>Eğer p &lt; 0.05 ise, o değişkenin modele anlamlı katkı sağladığı düşünülür.</p>
</blockquote>
<h3 id="ℹ-std.-error-nedir">ℹ️ Std. Error Nedir?</h3>
<blockquote>
<p><strong>Std. Error (Standart Hata)</strong>, tahmin edilen regresyon katsayısının (β̂) <strong>ne kadar belirsiz olduğunu</strong> ölçer.<br>
Başka bir deyişle, <strong>katsayının örnekleme dağılımının standart sapmasıdır</strong>.</p>
</blockquote>
<ul>
<li>Eğer <strong>standart hata küçükse</strong>, bu katsayıya daha fazla güvenebiliriz.</li>
<li>Eğer büyükse, örneklemdeki rastgelelik bu katsayının değerine daha çok etki ediyor olabilir.</li>
</ul>
<blockquote>
<p>🔎 <strong>İyi bir model</strong> genellikle anlamlı katsayılar + küçük standart hatalara sahiptir.</p>
</blockquote></li>
</ol>
</section>
<section class="slide level2">

<h3 id="faydalı-tavsiyeler">🧠 Faydalı Tavsiyeler</h3>
<h4 id="broom-paketi-kullan-daha-okunabilir-sonuçlar">✔️ <code>broom</code> paketi kullan: Daha okunabilir sonuçlar</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">library</span>(broom)</span>
<span id="cb8-2"><a href=""></a></span>
<span id="cb8-3"><a href=""></a><span class="fu">glance</span>(model1)      <span class="co"># Model düzeyinde özet istatistikler</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.544         0.543  6.22      602. 5.08e-88     1 -1641. 3289. 3302.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">tidy</span>(model1)        <span class="co"># Katsayılar, SE, p-değerleri</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   34.6      0.563       61.4 3.74e-236
2 lstat         -0.950    0.0387     -24.5 5.08e- 88</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="fu">augment</span>(model1)     <span class="co"># Gözlem düzeyinde hatalar, tahminler, artıklar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 506 × 8
    medv lstat .fitted .resid    .hat .sigma     .cooksd .std.resid
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
 1  24    4.98   29.8  -5.82  0.00426   6.22 0.00189        -0.939 
 2  21.6  9.14   25.9  -4.27  0.00246   6.22 0.000582       -0.688 
 3  34.7  4.03   30.7   3.97  0.00486   6.22 0.00100         0.641 
 4  33.4  2.94   31.8   1.64  0.00564   6.22 0.000198        0.264 
 5  36.2  5.33   29.5   6.71  0.00406   6.21 0.00238         1.08  
 6  28.7  5.21   29.6  -0.904 0.00413   6.22 0.0000440      -0.146 
 7  22.9 12.4    22.7   0.155 0.00198   6.22 0.000000620     0.0250
 8  27.1 19.2    16.4  10.7   0.00362   6.20 0.00544         1.73  
 9  16.5 29.9     6.12 10.4   0.0136    6.20 0.0194          1.68  
10  18.9 17.1    18.3   0.592 0.00274   6.22 0.0000125       0.0954
# ℹ 496 more rows</code></pre>
</div>
</div>
<h4 id="r²-yorumlanırken-dikkatli-ol">✔️ R² yorumlanırken dikkatli ol:</h4>
<ul>
<li>Çok yüksek olması her zaman iyi değildir</li>
<li>Düşük olabilir ama model doğru bir ilişkiyi temsil ediyor olabilir</li>
</ul>
<h4 id="confint-fonksiyonu-ile-güven-aralığına-bak">✔️ <code>confint()</code> fonksiyonu ile güven aralığına bak</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">confint</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %     97.5 %
(Intercept) 33.448457 35.6592247
lstat       -1.026148 -0.8739505</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="ekstra-bilgi-sigma">📌 Ekstra Bilgi: <code>sigma</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="fu">sigma</span>(model1)  <span class="co"># Ortalama artık hatasının tahmini (residual std error)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.21576</code></pre>
</div>
</div>
<blockquote>
<p>Bu değer “gerçek veri ile modelin tahminleri ortalama ne kadar sapıyor?” sorusunun cevabıdır.</p>
</blockquote>
<h3 id="yorum-1">💡 Yorum</h3>
<ul>
<li><code>lstat</code> değişkeni 1 birim arttığında (örneğin %12 → %13), medv <strong>ortalama β₁ kadar azalır</strong><br>
</li>
<li>Eğer bu katsayı negatifse, düşük sosyo-ekonomik oran <strong>arttıkça</strong> konut değeri <strong>azalıyor</strong> demektir<br>
</li>
<li>Bu bulgu anlamlıysa (p &lt; 0.001), veri içindeki ilişki güçlüdür</li>
</ul>
</section>
<section class="slide level2">

<h3 id="regresyon-doğrusu-ve-artıklar">📉 Regresyon Doğrusu ve Artıklar</h3>
<div class="columns">
<div class="column" style="width:90%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-2"><a href=""></a></span>
<span id="cb18-3"><a href=""></a><span class="fu">ggplot</span>(Boston, <span class="fu">aes</span>(<span class="at">x =</span> lstat, <span class="at">y =</span> medv)) <span class="sc">+</span></span>
<span id="cb18-4"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href=""></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href=""></a>  <span class="fu">labs</span>(</span>
<span id="cb18-7"><a href=""></a>    <span class="at">title =</span> <span class="st">"Basit Doğrusal Regresyon: medv ~ lstat"</span>,</span>
<span id="cb18-8"><a href=""></a>    <span class="at">x =</span> <span class="st">"% düşük statüdeki insanlar (lstat)"</span>,</span>
<span id="cb18-9"><a href=""></a>    <span class="at">y =</span> <span class="st">"Ortalama Konut Değeri (medv)"</span></span>
<span id="cb18-10"><a href=""></a>  ) <span class="sc">+</span></span>
<span id="cb18-11"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="6.regression_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<blockquote>
<p>🔵 Mavi çizgi modelin tahmin ettiği regresyon doğrusudur.<br>
Noktaların bu doğruya uzaklığı <strong>artık değerlerdir</strong> ve modelin ne kadar sapma yaptığını gösterir.</p>
</blockquote>
<h3 id="not">🧠 Not</h3>
<blockquote>
<p>Bu model yalnızca <strong>doğrusal bir ilişki</strong> varsayar.<br>
Ama bu ilişki her zaman doğrusal olmayabilir — grafik bu varsayımı test etmek için önemlidir.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="gözlem-bazlı-regresyon-analizi-artıklar-ve-tahminler">🧮 Gözlem Bazlı Regresyon Analizi – Artıklar ve Tahminler</h3>
<h3 id="amaç">🎯 Amaç:</h3>
<blockquote>
<p>Model her bir gözlem için ne kadar doğru tahmin yapıyor?<br>
Artıklar ne kadar büyük? Sistematik sapma var mı?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">library</span>(broom)</span>
<span id="cb19-2"><a href=""></a></span>
<span id="cb19-3"><a href=""></a><span class="co"># augment ile detaylı çıktı</span></span>
<span id="cb19-4"><a href=""></a>augmented <span class="ot">&lt;-</span> <span class="fu">augment</span>(model1)</span>
<span id="cb19-5"><a href=""></a></span>
<span id="cb19-6"><a href=""></a><span class="co"># İlk 6 gözlem için çıktıya bakalım</span></span>
<span id="cb19-7"><a href=""></a><span class="fu">head</span>(augmented)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
   medv lstat .fitted .resid    .hat .sigma   .cooksd .std.resid
  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1  24    4.98    29.8 -5.82  0.00426   6.22 0.00189       -0.939
2  21.6  9.14    25.9 -4.27  0.00246   6.22 0.000582      -0.688
3  34.7  4.03    30.7  3.97  0.00486   6.22 0.00100        0.641
4  33.4  2.94    31.8  1.64  0.00564   6.22 0.000198       0.264
5  36.2  5.33    29.5  6.71  0.00406   6.21 0.00238        1.08 
6  28.7  5.21    29.6 -0.904 0.00413   6.22 0.0000440     -0.146</code></pre>
</div>
</div>
<h3 id="önemli-kolonlar">📊 Önemli Kolonlar</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Kolon</th>
<th>Açıklama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>.fitted</code></td>
<td>Modelin tahmin ettiği medv değeri</td>
</tr>
<tr class="even">
<td><code>.resid</code></td>
<td>Artık değeri: <span class="math inline">\(y_i - \hat{y}_i\)</span></td>
</tr>
<tr class="odd">
<td><code>.std.resid</code></td>
<td>Standardize artık (çıkıntılı gözlemleri tespit için)</td>
</tr>
<tr class="even">
<td><code>.hat</code></td>
<td>Leverage değeri (etkili gözlem mi?)</td>
</tr>
<tr class="odd">
<td><code>.sigma</code></td>
<td>Tahminin hata tahmini (her gözlem için)</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="görselleştirme-tahmin-vs-gerçek">📉 Görselleştirme: Tahmin vs Gerçek</h3>
<div class="columns">
<div class="column" style="width:90%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-2"><a href=""></a></span>
<span id="cb21-3"><a href=""></a><span class="fu">ggplot</span>(augmented, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> medv)) <span class="sc">+</span></span>
<span id="cb21-4"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href=""></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href=""></a>  <span class="fu">labs</span>(</span>
<span id="cb21-7"><a href=""></a>    <span class="at">title =</span> <span class="st">"Tahmin Edilen vs Gerçek Değerler"</span>,</span>
<span id="cb21-8"><a href=""></a>    <span class="at">x =</span> <span class="st">"Tahmin (fitted)"</span>,</span>
<span id="cb21-9"><a href=""></a>    <span class="at">y =</span> <span class="st">"Gerçek (medv)"</span></span>
<span id="cb21-10"><a href=""></a>  ) <span class="sc">+</span></span>
<span id="cb21-11"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="6.regression_files/figure-revealjs/unnamed-chunk-10-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<blockquote>
<p>🔴 Kırmızı çizgi tam tahmin çizgisidir: <span class="math inline">\(\hat{y} = y\)</span><br>
Noktalar bu çizgiden çok sapıyorsa model orada başarısızdır.</p>
</blockquote>
<h3 id="tavsiye">🧠 Tavsiye:</h3>
<ul>
<li><code>.std.resid</code> &gt; 2 olan gözlemleri <strong>potansiyel uç değer</strong> olarak işaretleyin.</li>
<li><code>.hat</code> değeri yüksekse gözlem model üzerinde <strong>orantısız etki yaratıyor</strong> olabilir.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-2"><a href=""></a>augmented <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href=""></a>  <span class="fu">filter</span>(<span class="fu">abs</span>(.std.resid) <span class="sc">&gt;</span> <span class="dv">2</span> <span class="sc">|</span> .hat <span class="sc">&gt;</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 8
    medv lstat .fitted .resid    .hat .sigma .cooksd .std.resid
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1  43.8  3.57   31.2    12.6 0.00518   6.20 0.0108        2.04
 2  14.4 34.4     1.86   12.5 0.0204    6.20 0.0432        2.04
 3  50    1.73   32.9    17.1 0.00661   6.17 0.0253        2.76
 4  50    1.92   32.7    17.3 0.00645   6.17 0.0252        2.79
 5  50    3.32   31.4    18.6 0.00536   6.17 0.0243        3.00
 6  50    3.7    31.0    19.0 0.00509   6.16 0.0239        3.06
 7  39.8  7.56   27.4    12.4 0.00298   6.20 0.00600       2.00
 8  50    4.45   30.3    19.7 0.00459   6.16 0.0232        3.17
 9  50    2.97   31.7    18.3 0.00562   6.17 0.0245        2.95
10  48.5  3.81   30.9    17.6 0.00501   6.17 0.0202        2.83
# ℹ 22 more rows</code></pre>
</div>
</div>
</section>
<section id="regresyon-modeli-nasıl-değerlendirilir" class="slide level2">
<h2>📏 Regresyon Modeli Nasıl Değerlendirilir?</h2>
<h3 id="neden-gerekli">🔍 Neden Gerekli?</h3>
<blockquote>
<p>Modelin ne kadar iyi tahmin yaptığı sadece <span class="math inline">\(R^2\)</span> ile anlaşılmaz.<br>
Gerçek değerlerden ortalama ne kadar sapma olduğunu da bilmeliyiz.</p>
</blockquote>
<h3 id="temel-metrikler">📊 Temel Metrikler</h3>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Metrik</th>
<th>Açıklama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>RMSE</strong></td>
<td>Ortalama karekök hata: büyük hatalar daha çok cezalandırılır</td>
</tr>
<tr class="even">
<td><strong>MAE</strong></td>
<td>Ortalama mutlak hata: yorumlaması kolay</td>
</tr>
<tr class="odd">
<td><strong>R²</strong></td>
<td>Açıklanan varyans oranı</td>
</tr>
<tr class="even">
<td><strong>Adjusted R²</strong></td>
<td>Değişken sayısına göre düzeltilmiş R²</td>
</tr>
<tr class="odd">
<td><strong>AIC / BIC</strong></td>
<td>Model karşılaştırması: daha düşük daha iyidir</td>
</tr>
<tr class="even">
<td><strong>sigma()</strong></td>
<td>Ortalama artık sapması (residual std error)</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="uygulama-r-ile-hesaplama">🧪 Uygulama – R ile Hesaplama</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">library</span>(Metrics)</span>
<span id="cb24-2"><a href=""></a></span>
<span id="cb24-3"><a href=""></a>actual <span class="ot">&lt;-</span> Boston<span class="sc">$</span>medv</span>
<span id="cb24-4"><a href=""></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1)</span>
<span id="cb24-5"><a href=""></a></span>
<span id="cb24-6"><a href=""></a><span class="fu">rmse</span>(actual, predicted)   <span class="co"># Ortalama hata miktarı</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.203464</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">mae</span>(actual, predicted)    <span class="co"># Ortalama mutlak hata</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.505281</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="fu">sigma</span>(model1)             <span class="co"># summary(model1) içindeki residual std error</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.21576</code></pre>
</div>
</div>
<h4 id="ek-olarak">Ek olarak:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="fu">glance</span>(model1)[, <span class="fu">c</span>(<span class="st">"r.squared"</span>, <span class="st">"adj.r.squared"</span>, <span class="st">"AIC"</span>, <span class="st">"BIC"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  r.squared adj.r.squared   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.544         0.543 3289. 3302.</code></pre>
</div>
</div>
<blockquote>
<p>🔍 <code>glance()</code> ile performans metriklerine tek satırda ulaşılır.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="tavsiyeler">📌 Tavsiyeler:</h3>
<ul>
<li>RMSE ve MAE birlikte kullanılır → Biri sapmaları büyütür, diğeri sadeleştirir</li>
<li>AIC/BIC sadece <strong>aynı hedef değişkenli modeller</strong> arasında karşılaştırma için anlamlıdır</li>
<li>Çok yüksek R² bazen <strong>overfitting</strong> (ezberleme) anlamına da gelebilir</li>
<li>Sigma küçükse, artıklar küçük → iyi bir şey</li>
</ul>
<h3 id="kural">💡 Kural</h3>
<blockquote>
<p>Performans metriğini yorumlarken:<br>
<strong>“Tahmin ettiğim değer, ortalama olarak gerçek değerden ne kadar sapıyor?”</strong><br>
sorusuna cevap arıyoruz.</p>
</blockquote>
</section>
<section id="çoklu-doğrusal-regresyon" class="slide level2">
<h2>🧪 Çoklu Doğrusal Regresyon</h2>
<h3 id="amaç-1">🎯 Amaç:</h3>
<blockquote>
<p>Fiyatları etkileyebileceğini düşündüğümüz değişkenlerle daha gerçekçi bir model kurmak</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> lstat <span class="sc">+</span> rm <span class="sc">+</span> age <span class="sc">+</span> crim, <span class="at">data =</span> Boston)</span>
<span id="cb32-2"><a href=""></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat + rm + age + crim, data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.105  -3.501  -1.143   1.968  28.180 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.34910    3.17079  -0.741  0.45913    
lstat       -0.61258    0.05642 -10.857  &lt; 2e-16 ***
rm           5.11625    0.45083  11.349  &lt; 2e-16 ***
age          0.01259    0.01116   1.129  0.25950    
crim        -0.10639    0.03216  -3.308  0.00101 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.488 on 501 degrees of freedom
Multiple R-squared:  0.6468,    Adjusted R-squared:  0.6439 
F-statistic: 229.3 on 4 and 501 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<h3 id="ilk-yorumlar">🔍 İlk Yorumlar</h3>
<ul>
<li>Her bir değişkenin <strong>etkisi sabitken diğer değişkenin etkisi</strong> yorumlanır<br>
→ Örn: <code>lstat</code> 1 birim artarken, <code>rm</code>, <code>age</code>, <code>crim</code> sabit tutulur</li>
<li>p-değerleri sayesinde hangi değişkenlerin <strong>istatistiksel olarak anlamlı</strong> olduğu anlaşılır</li>
<li>Adjusted R² = çok önemli! Değişken sayısı arttığında R² her zaman yükselir, ama <strong>adj.R²</strong> artmazsa dikkat!</li>
</ul>
</section>
<section class="slide level2">

<h3 id="tahmin-ve-gerçek-değer-grafiği">📊 Tahmin ve Gerçek Değer Grafiği</h3>
<div class="columns">
<div class="column" style="width:90%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a><span class="fu">library</span>(broom)</span>
<span id="cb34-2"><a href=""></a>aug2 <span class="ot">&lt;-</span> <span class="fu">augment</span>(model2)</span>
<span id="cb34-3"><a href=""></a></span>
<span id="cb34-4"><a href=""></a><span class="fu">ggplot</span>(aug2, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> medv)) <span class="sc">+</span></span>
<span id="cb34-5"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href=""></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href=""></a>  <span class="fu">labs</span>(</span>
<span id="cb34-8"><a href=""></a>    <span class="at">title =</span> <span class="st">"Çoklu Model: Tahmin vs Gerçek Değer"</span>,</span>
<span id="cb34-9"><a href=""></a>    <span class="at">x =</span> <span class="st">"Tahmin (fitted)"</span>,</span>
<span id="cb34-10"><a href=""></a>    <span class="at">y =</span> <span class="st">"Gerçek (medv)"</span></span>
<span id="cb34-11"><a href=""></a>  ) <span class="sc">+</span></span>
<span id="cb34-12"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="6.regression_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<h3 id="yorum-2">💬 Yorum:</h3>
<blockquote>
<p>Çoklu model, <code>medv ~ lstat</code> tek başına olduğundan genellikle <strong>daha iyi</strong> sonuç verir.<br>
Ama <strong>anlamlılık</strong>, <strong>çoklu ilişki</strong> ve <strong>etki büyüklüğü</strong> gibi unsurları göz ardı etmemek gerekir.</p>
</blockquote>
</section>
<section id="çoklu-doğrusal-regresyonda-sık-yapılan-hatalar" class="slide level2">
<h2>⚠️ Çoklu Doğrusal Regresyonda Sık Yapılan Hatalar</h2>
<h3 id="tipik-hatalar">🚫 Tipik Hatalar</h3>
<ul>
<li><strong>Tüm değişkenleri körlemesine eklemek</strong> → Açıklayıcı güç değil, gürültü artar</li>
<li><strong>Korelasyon varsa mutlaka koymalıyım düşüncesi</strong> → Multikolineariteye yol açabilir</li>
<li><strong>Kategorik değişkenleri sayısal gibi bırakmak</strong> → Faktör dönüşümü yapılmadan model yanlış çalışır</li>
<li><strong>Artıkları ve varsayımları test etmemek</strong> → R² yüksek olsa da model istatistiksel olarak geçersiz olabilir</li>
<li><strong>R²’ye körü körüne güvenmek</strong> → Model iyi gözükür ama ezber yapıyor olabilir (overfitting)</li>
<li><strong>Veriyi incelemeden regresyona girmek</strong> → Lineerlik sağlanmıyor olabilir</li>
</ul>
</section>
<section class="slide level2">

<h4 id="vif-ile-multikolineariteyi-kontrol-et">✔️ VIF ile Multikolineariteyi Kontrol Et</h4>
<p>VIF (Variance Inflation Factor) ile çoklu doğrusal ilişkiyi kontrol et</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="fu">library</span>(car)</span>
<span id="cb35-2"><a href=""></a><span class="fu">vif</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   lstat       rm      age     crim 
2.721744 1.682348 1.653431 1.282924 </code></pre>
</div>
</div>
<blockquote>
<p>🔍 VIF &gt; 5 → <strong>ciddi çoklu ilişki riski</strong>,<br>
VIF &gt; 10 → <strong>kritik düzeyde uyarı</strong></p>
</blockquote>
</section>
<section class="slide level2">

<h4 id="performance-paketi-ile-hızlı-model-testi">✔️ <code>performance</code> paketi ile hızlı model testi</h4>
<h3 id="amaç-2">🎯 Amaç:</h3>
<blockquote>
<p>Regresyon modelinin varsayımlarını <strong>tek adımda test etmek</strong><br>
Artıkların dağılımı, varyans sabitliği, lineerlik, normal dağılım ve uç değerler dahil</p>
</blockquote>
<div class="columns">
<div class="column" style="width:95%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a><span class="fu">library</span>(performance)</span>
<span id="cb37-2"><a href=""></a><span class="fu">check_model</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="6.regression_files/figure-revealjs/unnamed-chunk-17-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<h3 id="üretilen-grafikler-ve-yorumları">📊 Üretilen Grafikler ve Yorumları</h3>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 33%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Grafik</th>
<th>Ne Gösterir?</th>
<th>Nasıl Yorumlanır?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Posterior Predictive Check</strong></td>
<td>Histogram veya yoğunluk grafiği olarak verilir.</td>
<td>Modelin tahmin ettiği değerlerin, gerçek değerlerle <strong>benzer dağılıma</strong> sahip olup olmadığını kontrol eder.</td>
</tr>
<tr class="even">
<td><strong>Linearity Check</strong></td>
<td>Fitted vs Residuals</td>
<td>Noktalar rastgele dağılmalı. Desen varsa lineerlik sağlanmıyor.</td>
</tr>
<tr class="odd">
<td><strong>Homoscedasticity</strong></td>
<td>Artıkların sabit varyansı</td>
<td>Fan açılıyorsa heteroskedastisite olabilir.</td>
</tr>
<tr class="even">
<td><strong>Normality of Residuals</strong></td>
<td>QQ Plot</td>
<td>Noktalar eğriden sapıyorsa normal dağılım varsayımı bozulmuş olabilir.</td>
</tr>
<tr class="odd">
<td><strong>Outliers</strong></td>
<td>Standardize artıklar ve leverage</td>
<td>Uzak noktalar varsa, potansiyel etkili uç gözlemler olabilir.</td>
</tr>
<tr class="even">
<td><strong>Influential Obs.</strong></td>
<td>Cook’s Distance</td>
<td>.5 üzeri değerler varsa dikkat: gözlem modeli etkiliyor olabilir.</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="dikkat-edilmesi-gerekenler">📌 Dikkat Edilmesi Gerekenler</h3>
<ul>
<li><strong>Lineerlik bozulmuşsa</strong> → modelin formunu değiştir (log, polinomik dönüşüm)</li>
<li><strong>Heteroskedastisite varsa</strong> → <code>lmtest::bptest()</code> ile test et, <code>robust</code> modelleri düşün</li>
<li><strong>QQ plot bozuksa</strong> → çıkarım yaparken dikkat et, normal varsayımı önemliyse <code>glm</code> düşün</li>
<li><strong>Leverage ve Cook’s D. yüksekse</strong> → gözlemi silmeden önce etkisini analiz et</li>
</ul>
<h3 id="tavsiye-1">🧠 Tavsiye</h3>
<blockquote>
<p><code>check_model()</code> sonucu sadece görüp geçilmez.<br>
Her bir grafiği modelin anatomik bir MR’ı gibi düşün.<br>
Varsayımlar sağlanmıyorsa: <strong>model değiştirilir ya da dönüştürülür.</strong></p>
</blockquote>
</section>
<section class="slide level2">

<h4 id="kategorik-değişkenler-için-factor-kullan">✔️ Kategorik Değişkenler için <code>factor()</code> kullan</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a>Boston<span class="sc">$</span>chas <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Boston<span class="sc">$</span>chas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<h3 id="hatırlatma">🎓 Hatırlatma</h3>
<blockquote>
<p><strong>İyi bir regresyon modeli</strong>, sadece yüksek R² değil;<br>
anlamlı katsayılar, düşük multikolinearite, tutarlı varsayımlar ve yorumlanabilirlik içerir.</p>
</blockquote>
</section>
<section id="doğrusal-regresyonda-kullanılabilecek-ileri-araçlar" class="slide level2">
<h2>🧰 Doğrusal Regresyonda Kullanılabilecek İleri Araçlar</h2>
<h3 id="öne-çıkan-paketler-ve-amaçları">📦 Öne Çıkan Paketler ve Amaçları</h3>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 23%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Paket</th>
<th>Amaç</th>
<th>Notlar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>broom</code></td>
<td>Regresyon çıktısını düzenleme</td>
<td><code>tidy()</code>, <code>glance()</code>, <code>augment()</code> fonksiyonları</td>
</tr>
<tr class="even">
<td><code>car</code></td>
<td>Varsayım testi, multikolinearite</td>
<td><code>vif()</code>, <code>linearHypothesis()</code></td>
</tr>
<tr class="odd">
<td><code>performance</code></td>
<td>Model varsayımları, etkili gözlem tespiti</td>
<td><code>check_model()</code> ile tam analiz</td>
</tr>
<tr class="even">
<td><code>modelsummary</code></td>
<td>Yayın kalitesinde regresyon tabloları</td>
<td>Çoklu model karşılaştırması kolay</td>
</tr>
<tr class="odd">
<td><code>ggfortify</code></td>
<td>Regresyon için otomatik artık grafikleri</td>
<td><code>autoplot(lm_model)</code></td>
</tr>
<tr class="even">
<td><code>glmnet</code></td>
<td>Ridge, Lasso, Elastic Net</td>
<td>Regularizasyon için</td>
</tr>
<tr class="odd">
<td><code>tidymodels</code></td>
<td>Modern modelleme altyapısı</td>
<td><code>recipes</code>, <code>workflow</code>, <code>tune</code>, <code>parsnip</code></td>
</tr>
<tr class="even">
<td><code>jtools</code></td>
<td>Regresyon grafiklendirme, etkili sunum</td>
<td><code>summ()</code>, <code>plot_summs()</code></td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="ne-zaman-kullanılır">🧠 Ne Zaman Kullanılır?</h3>
<ul>
<li><strong>Modeli yorumlamak için</strong>: <code>broom</code>, <code>modelsummary</code>, <code>jtools</code></li>
<li><strong>Varsayımları test etmek için</strong>: <code>performance</code>, <code>car</code></li>
<li><strong>Görselleştirme için</strong>: <code>ggplot2</code>, <code>ggfortify</code>, <code>jtools</code></li>
<li><strong>Gelişmiş regresyon için</strong>: <code>glmnet</code>, <code>tidymodels</code></li>
<li><strong>Sunum/rapor üretmek için</strong>: <code>modelsummary</code>, <code>stargazer</code> (LaTeX için)</li>
</ul>
</section>
<section class="slide level2">

<h3 id="faydalı-kaynaklar">📚 Faydalı Kaynaklar</h3>
<ul>
<li>📖 <em>An Introduction to Statistical Learning</em> (ISLR)<br>
</li>
<li>📖 <em>Hands-On Machine Learning with R</em> – Brad Boehmke &amp; Brandon Greenwell<br>
</li>
<li>🔗 <a href="https://www.tidymodels.org/">tidymodels.org</a> – modern modelleme ekosistemi<br>
</li>
<li>🔗 <a href="https://easystats.github.io/performance">easystats.github.io/performance</a> – varsayım kontrolleri</li>
</ul>
<h3 id="kapanış-tavsiyesi">🎯 Kapanış Tavsiyesi</h3>
<blockquote>
<p>Doğrusal regresyon, sadece “ilk model” değil, çoğu zaman <strong>en güçlü referans modeldir</strong>.<br>
Modern araçlarla desteklenirse hem sağlam, hem de sürdürülebilir analizler yapılabilir.</p>
</blockquote>
</section>
<section class="slide level2">

<h3 id="neler-öğrendik">📚 Neler Öğrendik?</h3>
<ul>
<li><strong>Doğrusal Regresyonun temel mantığı</strong>: Bağımlı ve bağımsız değişkenler arasındaki ilişki</li>
<li><strong>Parametre tahmini, artıklar, varsayımlar</strong></li>
<li><strong>Basit ve çoklu modellerle uygulama</strong> (<code>lm</code>, <code>summary</code>, <code>augment</code>)</li>
<li><strong>Model değerlendirme metrikleri</strong>: RMSE, MAE, R², AIC</li>
<li><strong>Varsayım kontrolleri</strong> (<code>check_model</code>, <code>vif</code>)</li>
<li><strong>Regresyonu anlamlı kılan şey: yorumlama, sadeleşme, kontrol</strong></li>
</ul>
<h3 id="tavsiyeler-1">🔧 Tavsiyeler</h3>
<ul>
<li>Her modeli <strong>yorumla</strong>, sadece <strong>hesaplama</strong> yapma</li>
<li><strong>Varsayımlar bozulduğunda</strong> bileceğin araçlar olsun</li>
<li>Regresyon = Makine öğrenmesine açılan <strong>istatistiksel kapı</strong></li>
</ul>
</section>
<section class="slide level2">

<h3 id="teşekkürler">🙏 Teşekkürler</h3>
<blockquote>
<p>Katılımınız için teşekkür ederim!<br>
📧 İletişim: <strong>Dr.&nbsp;M. Fatih Tüzen</strong></p>
<blockquote>
<p>📧 fatih.tuzen@tuik.gov.tr<br>
🌐 <a href="https://rprogramlama.netlify.app">rprogramlama.netlify.app</a><br>
🔗 <a href="https://www.linkedin.com/in/dr-m-fatih-t-2b2a4328/">linkedin.com/in/dr-m-fatih-t-2b2a4328</a></p>
</blockquote>
</blockquote>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/TUiK_logo_Tr.jpg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Altıncı Uluslararası Uygulamalı İstatistik Kongresi (UYIK 2025)</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="6.regression_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="6.regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="6.regression_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="6.regression_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>